---

- name: set vm.swappiness
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
  when sysctl_enable
 
- name: set ip forward
  sysctl:
    name: net.ipv4.ip_forward
    vales: 1
    sysctl_set: yes
  when sysctl_enable

- name: set ip forward in the sysctl file and reload
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes 
  when sysctl_enable
