---



    #config ntp server
    - name: add ntp server crontab
      cron:
        name: ntp server
        hour: "*/2"
        job: /usr/sbin/ntpdate -u {{ ntp_server }}

    - name: config ntp server
      shell: /usr/sbin/ntpdate -u {{ ntp_server }}
