---    


- name: create backup file
  file: path=/etc/yum.repos.d/bak state=directory

- name: backup repo file
  shell: mv /etc/yum.repos.d/*.repo /etc/yum.repos.d/bak
  ignore_errors: True

- name: copy local repo file
  copy: src={{ item }} dest=/etc/yum.repos.d/
  with_items:
    - Centos-{{ ansible_distribution_major_version }}.repo
    - epel-{{ ansible_distribution_major_version }}.repo
  register: result
  ignore_errors: yes

- name: download remote repo file
  get_url: url={{ item }} dest=/etc/yum.repos.d/
  with_items:
    - http://mirrors.aliyun.com/repo/Centos-{{ ansible_distribution_major_version }}.repo
    - http://mirrors.aliyun.com/repo/epel-{{ ansible_distribution_major_version }}.repo
  when: ansible_os_family == 'RedHat' and result['changed'] == false
