---


    # config selinux
    - name: config selinux
      lineinfile: path='/etc/selinux/config' regexp='^SELINUX=' line='SELINUX=enforcing'

    - name: set sentenforce
      shell: setenforce 0

    #config iptables
    - name: config iptables
      service: name=iptables state=stopped enabled=no
      when: ansible_os_family == 'RedHat' and ansible_distribution_version == '6.9'
