---


    - name: create directory
      file: path=/root/.ssh state=directory owner=root group=root mode=700

#    - name: copy id_rsa file
#      copy: src=/root/.ssh/id_rsa dest=/root/.ssh/ owner=root group=root mode=600

    - name: generation authorized_keys file
      copy: src=files/authorized_keys dest=/root/.ssh/ owner=root group=root mode=600

    - name: modify config
      lineinfile: dest=/etc/ssh/sshd_config regexp='^#{{ item }}' line='{{ item }}' backrefs=yes
      with_items:
        - RSAAuthentication yes
        - PubkeyAuthentication yes
        - AuthorizedKeysFile      .ssh/authorized_keys

    - name: modify UseDNS
      lineinfile: dest=/etc/ssh/sshd_config regexp='#UseDNS' line='UseDNS no' backrefs=yes

    - name: modify PasswordAuthentication
      lineinfile: dest=/etc/ssh/sshd_config regexp='PasswordAuthentication yes' line='PasswordAuthentication no' backrefs=yes

    - name: start centos7 sshd
      systemd : name=sshd state=started enabled=yes
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "7"
      tags:
        - ssh

    
    - name: start centos6 sshd
      systemd: name=sshd state=started enabled=yes
      when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == "6"
      tags:
        - ssh
