---


- name: create web directory
  file: path={{ nginx_web_root }}   state=directory owner=www group=www

- name: config nginx
  template: src=nginx.conf.j2 dest=/usr/local/nginx/conf/nginx.conf
  notify:
    - restart nginx


- name: start nginx
  systemd: name=nginx state=started
